import './globals.css'
import { Inter } from 'next/font/google'

import { BottomNavigation, Breadcrumbs, Header } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center fixed w-full z-[1000] bg-base-100">
          <Header />
        </header>
        <main className="min-h-[calc(100vh-4rem)] flex-col pt-20 px-4 bg-base-100">
          <Breadcrumbs />
          {children}
        </main>
        <BottomNavigation />
      </body>
    </html>
  )
}

